---
apiVersion: v1
kind: Secret
metadata:
  name: taxonworks
  namespace: tw
type: Opaque
data:
  db.root.password: dHdwYXNzd29yZA== # twpassword
  db.user: dHc= # tw
  db.user.password: dHdwYXNzd29yZA== # twpassword
  secret_key_base: NmMyMjMyZDU1Mzc1YzdjMzllZTlkYTNhNTBkMTNkY2Q3MmI1MTk5ODg4MzU0ZGZjZGQ1N2NjYzE1MDIyMjM2YTUxOGU0ZjlhYTc5MTU0ZWMyNDQ0M2E5NjBhYWVlZTcxM2UyMTYwZmY1MWEzYWE1MjMwNDBhN2QxNDM3OWVjNDM=
