# Documentation: http://www.rubydoc.info/gems/rubocop
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true

Style/EmptyLineBetweenDefs:
  # If true, this parameter means that single line method definitions don't
  # need an empty line between them.
  AllowAdjacentOneLineDefs: true

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/ClassAndModuleChildren:
  EnforcedStyle: compact 

Style/CaseIndentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false
  AllowForAlignment: false
  ForceEqualSignAlignment: true

Style/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Metrics/LineLength:
  Max: 250
# Use empty lines between defs.

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 600

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 1000

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Rails/FindBy:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb

Rails/FindEach:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb

Rails/ReadWriteAttribute:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb

Rails/ScopeArgs:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb

Rails/Validation:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb
