inherit_from: .rubocop_todo.yml

# Documentation: http://www.rubydoc.info/gems/rubocop
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.yardoc/**/*'
    - '.idea/**/*'
    - '.bundle/**/*'
    - 'coverage/**/*'
    - 'volumes/**/*'
    - 'public/packs/**/*'
    - 'public/packs-test/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true

#Style/StringHashKeys:
#  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
#  AutoCorrect: false

Metrics/MethodLength:
  Enabled: true
  CountComments: true
  Max: 25

Metrics/ClassLength:
  Enabled: true
  CountComments: true
  Max: 1000
