inherit_from: .rubocop_todo.yml

# Documentation: http://www.rubydoc.info/gems/rubocop
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  MaxFilesInCache: 8000 # Limit growth of cache
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.yardoc/**/*'
    - '.idea/**/*'
    - '.bundle/**/*'
    - 'coverage/**/*'
    - 'volumes/**/*'
    - 'public/packs/**/*'
    - 'public/packs-test/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true
#  AutoCorrect: false

Style/StringHashKeys:
  Enabled: false

Style/HashSyntax:
  Enabled: false
  EnforcedStyle: ruby19
#  AutoCorrect: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 25

Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 1000

Layout/IndentationWidth:
  Enabled: false
  Width: 2

# TODO: select possible additions by setting `Enabled: true`

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Lint/DuplicateCaseCondition:
  Enabled: true
