inherit_from: .rubocop_todo.yml

# Documentation: http://www.rubydoc.info/gems/rubocop
AllCops:
  DisabledByDefault: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.yardoc/**/*'
    - '.idea/**/*'
    - '.bundle/**/*'
    - 'coverage/**/*'
    - 'volumes/**/*'
    - 'public/packs/**/*'
    - 'public/packs-test/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true


