language: ruby
sudo: false
rvm:
  - 2.1.5
bundler_args: --without development
branches:
  only:
      - master
addons:
  postgresql: "9.3"
  apt:
    packages:
      - libgeos-dev
      - libproj-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml.example config/database.yml
  - psql -U postgres -c 'create role taxonworks_development login createdb superuser;' 
  - rake db:drop  
  - rake db:create
  - rake db:migrate
  - rake db:migrate HPS_ENV=test 
notifications:
  email:
    - diapriid@gmail.com 
  on_failure: change
