dist: bionic
branches:
  only:
    - master
    - development
    - staged-imports
    - /v\d+\.\d+\.\d+(-.+)?/
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
jobs:
  allow_failures:
  - env: TEST_WORKER=1
  - env: TEST_WORKER=2
  - env: TEST_WORKER=3
  - env: TEST_WORKER=4
  - env: TEST_WORKER=5

  include:
    - &test-stage
      stage: test
      if: NOT (tag =~ /\d+\.\d+\.\d+/)
      language: ruby
      cache:
        bundler: true
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
          - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
          - $TRAVIS_BUILD_DIR/public/packs-test
          - $TRAVIS_BUILD_DIR/public/assets
          - $TRAVIS_BUILD_DIR/tmp/cache/webpacker
          - /home/travis/.rvm/
      rvm:
        - 2.7.1
      bundler_args: --without development production
      addons:
        postgresql: "10"
        firefox: "79.0"
        apt:
          packages:
            - imagemagick
            - tesseract-ocr
            - libgeos-dev
            - libproj-dev
            - postgresql-10-postgis-2.4
      env:
          - TEST_WORKER=0
      services:
        - postgresql
      before_install:
        - nvm install 10
        - nvm use 10
      install:
        - npm install
        - gem install bundler
        - bundle config --local build.sassc --disable-march-tune-native
        - bundle install -j3 --without development production
      before_script:
        - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
        - cp config/application_settings.yml.travis config/application_settings.yml
        - cp config/database.yml.travis config/database.yml
        - cp config/secrets.yml.example config/secrets.yml
        - mkdir -p tmp/downloads
        - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis`
        - bundle exec rake db:migrate RAILS_ENV=test
      script:
        - .travis/spec_runner.sh
    - <<: *test-stage
      env:
        - TEST_WORKER=1
    - <<: *test-stage
      env:
        - TEST_WORKER=2
    - <<: *test-stage
      env:
        - TEST_WORKER=3
    - <<: *test-stage
      env:
        - TEST_WORKER=4
    - stage: deliver
      language: minimal
      services:
        - docker
      install:
        - export REVISION=$(git rev-parse HEAD | cut -c1-9)
        - cd .travis
        - docker build .. -t sfgrp/taxonworks --build-arg REVISION=$REVISION --build-arg BUNDLER_WORKERS=3
        - docker-compose build --parallel
        - docker-compose up -d --no-build
        - docker-compose logs
      script:
        - docker-compose exec test bundle exec rspec -fd && docker-compose exec taxonworks redis-cli ping
      after_success:
        - |
          [ "$TRAVIS_REPO_SLUG" == "SpeciesFileGroup/taxonworks" ] && \
          [ "$TRAVIS_EVENT_TYPE" == "push" ] && \
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && \
          docker tag sfgrp/taxonworks:latest sfgrp/taxonworks:staged-imports && \
          docker push sfgrp/taxonworks:staged-imports
notifications:
  email:
    recipients:
      - diapriid@gmail.com
      - ellocodelassembler@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
