language: ruby
rvm:
  - 2.0.0
bundler_args: --without development
branches:
  only:
      - master
before_install: ./travis/before_install.sh
before_script: 
  - cp config/database.yml.example config/database.yml
  - psql -U postgres -c 'create role taxonworks_development login createdb superuser;' 
  - rake db:setup
  #- ./travis/before_script.sh
  - rake db:migrate
  - rake db:migrate HPS_ENV=test 
