language: ruby 
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - /home/travis/.rvm/ 
dist: trusty
sudo: required
rvm:
  - 2.4.4
bundler_args: --without development production
branches:
  only:
    - master
    - development
    - rails52
addons:
  postgresql: "10"
  firefox: "latest"
  apt:
    update: true 
    packages:
      - libgeos-dev
      - libproj-dev
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
env:
  global:
    - PGPORT=5433
    - NODE_ENV=development
services:
  - postgresql
before_install:
  - nvm install node
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
  - sleep 3
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - mkdir tmp/
  - mkdir tmp/downloads
  - npm run increase-memory-limit
# - travis_wait 40 bundle exec rake assets:precompile RAILS_ENV=test
script:
  - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis` 
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
notifications:
  email:
    recipients:
      - diapriid@gmail.com
    on_failure: change
