language: minimal
services:
  - docker
cache:
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - $TRAVIS_BUILD_DIR/public/packs-test
    - $TRAVIS_BUILD_DIR/public/assets
    - $TRAVIS_BUILD_DIR/tmp/cache
    - /home/travis/docker-images
dist: xenial
branches:
  only:
    - master
    - development
    - dates
    - docker-travis
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_WORKER=1
before_install:
  - env | grep -E '^TRAVIS_' > .env
  - echo "TEST_WORKERS=$TEST_WORKERS" >> .env
  - echo "COVERALLS_PARALLEL=$COVERALLS_PARALLEL" >> .env
  - echo "RAILS_ENV=test" >> .env
  - echo "TEST_WORKER=$TEST_WORKER" >> .env
  - >
    [ ! -f $HOME/docker-images/tw-travis-image.tar ] || docker load -i $HOME/docker-images/tw-travis-image.tar
  - docker image ls --no-trunc --all
install:
  - sed  -i -e 's/^\s*spec\s*$//' .dockerignore
  - >
    docker build . -t tw-travis -f .travis/Dockerfile
    --build-arg UID=$(id -u) --build-arg GID=$(id -g)
    --build-arg RUBY_VERSION=$(cat Gemfile | grep -e "^ruby\s*.*$" | sed -E "s/[^']*'([^']*)'/ruby-\1/")
    --build-arg BUNDLER_VERSION=$(tail -n1 Gemfile.lock | tr -d '[:space:]')
  - >
    docker run -d --env-file .env
    -v "$TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes":/home/travis/app/spec/fixtures/vcr_cassettes
    -v "$TRAVIS_BUILD_DIR/public/packs-test":/home/travis/app/public/packs-test
    -v "$TRAVIS_BUILD_DIR/public/assets":/home/travis/app/public/assets
    -v "$TRAVIS_BUILD_DIR/tmp/cache":/home/travis/app/tmp/cache
    --name tw_container
    tw-travis
  - >
    until docker exec -it tw_container sudo -u postgres psql -c
    "CREATE ROLE travis SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;";
    do sleep 1; done
  - mkdir -p $HOME/docker-images
  - export IMAGE_ID=$(docker image ls tw-travis -q --no-trunc)
  - docker image ls --no-trunc --all
  - docker system prune --all -f
  - docker image ls --no-trunc --all
  - >
    ([ -f $HOME/docker-images/id ] && [ $(< $HOME/docker-images/id) == "$IMAGE_ID" ]) ||
    docker save -o $HOME/docker-images/tw-travis-image.tar $(docker images -q --all) &&
    docker image ls tw-travis -q --no-trunc > $HOME/docker-images/id
before_script:
  - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
  - docker exec -it tw_container bash -l -c "bundle exec rake db:create"
  - docker exec -it tw_container bash -l -c "bundle exec rake db:migrate"
script:
  - docker exec -it tw_container bash -l -c '.travis/spec_runner.sh'
notifications:
  email:
    recipients:
      - diapriid@gmail.com
      - ellocodelassembler@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
