language: ruby
rvm:
  - 2.0.0
bundler_args: --without development
branches:
  only:
      - postgres
before_install: ./travis/before_install.sh
before_script:
  - cp config/database.yml.example config/database.yml
  - rake db:create:all
  - rake db:migrate
