language: ruby 
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - $TRAVIS_BUILD_DIR/public/packs-test
    - /home/travis/.rvm/ 
dist: xenial
# sudo: required
rvm:
  - 2.5.1
bundler_args: --without development production
branches:
  only:
    - master
    - development
    - rails52
    - digitize
    - parallel_travis
addons:
  postgresql: "10"
  firefox: "latest"
  apt:
    update: true 
    packages:
      - imagemagick
      - libgeos-dev
      - libproj-dev
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
env:
  global:
    - TEST_WORKERS=8
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_WORKER=0
    - TEST_WORKER=1
    - TEST_WORKER=2
    - TEST_WORKER=3
    - TEST_WORKER=4
    - TEST_WORKER=5
    - TEST_WORKER=6
    - TEST_WORKER=7
services:
  - postgresql
before_install:
  - nvm install node
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - npm install
  - bundle install --without development production
before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
  - sleep 3
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - mkdir tmp/
  - mkdir tmp/downloads
  - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis` 
  - bundle exec rake db:migrate RAILS_ENV=test
  - ls -alh bin 
  - ls -alh public/packs-test
  - export SPEC_FILES=$(find spec/ -type f -name "*_spec.rb" | sort)
  - export SPEC_COUNT=$(echo $SPEC_FILES | wc -w)
  - export BEGIN_INDEX=$[($SPEC_COUNT + $TEST_WORKERS - 1) / $TEST_WORKERS * $TEST_WORKER + 1]
  - export END_INDEX=$[($SPEC_COUNT + $TEST_WORKERS - 1) / $TEST_WORKERS * ($TEST_WORKER + 1)]
script:
  - bundle exec rake assets:precompile
# - bundle exec parallel_test spec/ -n 6 --only-group $TEST_GROUP --group-by filesize --type rspec
  - bundle exec rspec $(echo $SPEC_FILES | cut -d " " -f $BEGIN_INDEX-$END_INDEX)
notifications:
  email:
    recipients:
      - diapriid@gmail.com
    on_failure: change
