dist: xenial
branches:
  only:
    - master
    - development
    - dates
    - docker-travis
    - build-with-assets
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - &test-stage
      stage: test
      language: ruby
      cache:
        bundler: true
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
          - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
          - $TRAVIS_BUILD_DIR/public/packs-test
          - $TRAVIS_BUILD_DIR/public/assets
          - $TRAVIS_BUILD_DIR/tmp/cache/webpacker
          - /home/travis/.rvm/
      rvm:
        - 2.5.1
      bundler_args: --without development production
      addons:
        postgresql: "10"
        firefox: "latest"
        apt:
          update: true
          packages:
            - imagemagick
            - libgeos-dev
            - libproj-dev
            - postgresql-10-postgis-2.4
            - postgresql-10-postgis-2.4-scripts
            - postgresql-10
            - postgresql-client-10
            - postgresql-contrib-10
      env:
          - TEST_WORKER=0
      services:
        - postgresql
      before_install:
        - nvm install 10.15.3
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
        - export PATH=$HOME/.yarn/bin:$PATH
        - export BUNDLER_VERSION=$(tail -n1 Gemfile.lock | tr -d '[:space:]')
      install:
        - npm install
        - gem install bundler --no-ri --no-rdoc -v $BUNDLER_VERSION
        - bundle install --without development production
      before_script:
        - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
        - cp config/application_settings.yml.travis config/application_settings.yml
        - cp config/database.yml.travis config/database.yml
        - cp config/secrets.yml.example config/secrets.yml
        - mkdir -p tmp/downloads
        - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis`
        - bundle exec rake db:migrate RAILS_ENV=test
      script:
        - .travis/spec_runner.sh
    - <<: *test-stage
      env:
        - TEST_WORKER=1
    - <<: *test-stage
      env:
        - TEST_WORKER=2
    - <<: *test-stage
      env:
        - TEST_WORKER=3
    - <<: *test-stage
      env:
        - TEST_WORKER=4
    - stage: deploy
      language: minimal
      services:
        - docker
      install:
        - export REVISION=$(git rev-parse --short HEAD)
        - docker build . -t sfgrp/taxonworks --build-arg REVISION=$REVISION
      script:
        - cd .travis && docker-compose up --build --exit-code-from test
notifications:
  email:
    recipients:
      - diapriid@gmail.com
      - ellocodelassembler@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
