language: ruby 
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - $TRAVIS_BUILD_DIR/public/packs-test
    - $TRAVIS_BUILD_DIR/public/assets
    - /home/travis/.rvm/ 
dist: xenial
# sudo: required
rvm:
  - 2.5.1
bundler_args: --without development production
branches:
  only:
    - master
    - development
    - rails52
    - digitize
    - parallel_travis
addons:
  postgresql: "10"
  firefox: "latest"
  apt:
    update: true 
    packages:
      - imagemagick
      - libgeos-dev
      - libproj-dev
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_WORKER=0
    - TEST_WORKER=1
    - TEST_WORKER=2
    - TEST_WORKER=3
    - TEST_WORKER=4
services:
  - postgresql
before_install:
  - nvm install node
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - npm install
  - bundle install --without development production
before_script:
  - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
  - sleep 3
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - mkdir tmp/
  - mkdir tmp/downloads
  - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis` 
  - bundle exec rake db:migrate RAILS_ENV=test
  - ls -alh bin 
  - ls -alh public/packs-test
script:
  - .travis/spec_runner.sh
notifications:
  email:
    recipients:
      - diapriid@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
