language: minimal
cache:
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - $TRAVIS_BUILD_DIR/public/packs-test
    - $TRAVIS_BUILD_DIR/public/assets
    - $TRAVIS_BUILD_DIR/tmp/cache/webpacker
    - /home/travis/docker
before_cache:
  - docker rm -f $(docker ps -aq)
  - docker run -d tw-travis-base true && docker run -d ubuntu:16.04 true
  - docker image prune --all -f
  - docker rm -f $(docker ps -aq)
  - export IMAGE_ID=$(docker image ls tw-travis-base -q --no-trunc)
  - sudo service docker stop
  - >
    ([ -f $HOME/docker/id ] && [ $(< $HOME/docker/id) == "$IMAGE_ID" ]) ||
    echo $IMAGE_ID > $HOME/docker-images/id &&
    sudo tar -czf $HOME/docker/storage.tar.gz /var/lib/docker
dist: xenial
branches:
  only:
    - master
    - development
    - dates
    - docker-travis
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST_WORKER=1
before_install:
  - env | grep -E '^TRAVIS' > $HOME/.env
  - env | grep -E '^COVERALLS' >> $HOME/.env
  - env | grep -E '^TEST_' >> $HOME/.env
  - echo "RAILS_ENV=test" >> $HOME/.env
  - echo "CI=true" >> $HOME/.env
  - mkdir -p $HOME/docker
  - >
    [ ! -f $HOME/docker/storage.tar.gz ] ||
    cd / && sudo tar -xf $HOME/docker/storage.tar.gz
  - sudo service docker start
  - docker version
  - docker image ls --no-trunc --all
install:
  - sed -i -e 's/^\s*spec\s*$//' .dockerignore
  - echo "spec/fixtures/vcr_cassettes" >> .dockerignore
  - cp Gemfile Gemfile.lock package.json package-lock.json .travis
  - >
    export TW_BUILD_ARGS="
    --build-arg UID=$(id -u) --build-arg GID=$(id -g)
    --build-arg RUBY_VERSION=$(cat Gemfile | grep -e "^ruby\s*.*$" | sed -E "s/[^']*'([^']*)'/ruby-\1/")
    --build-arg BUNDLER_VERSION=$(tail -n1 Gemfile.lock | tr -d '[:space:]')"
  - docker build --target tw-travis-base -t tw-travis-base .travis $TW_BUILD_ARGS
  - docker build -t tw-travis -f .travis/Dockerfile . $TW_BUILD_ARGS
  - >
    docker run -d --env-file $HOME/.env
    -v "$TRAVIS_BUILD_DIR/.git":/home/travis/app/.git
    -v "$TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes":/home/travis/app/spec/fixtures/vcr_cassettes
    -v "$TRAVIS_BUILD_DIR/public/packs-test":/home/travis/app/public/packs-test
    -v "$TRAVIS_BUILD_DIR/public/assets":/home/travis/app/public/assets
    -v "$TRAVIS_BUILD_DIR/tmp/cache":/home/travis/app/tmp/cache
    --name tw_container
    tw-travis
  - >
    until docker exec -it tw_container sudo -u postgres psql -c
    "CREATE ROLE travis SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;";
    do sleep 1; done
before_script:
  - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
  - docker exec -it tw_container bash -l -c "bundle exec rake db:create"
  - docker exec -it tw_container bash -l -c "bundle exec rake db:migrate"
script:
  - docker exec -it tw_container bash -l -c '.travis/spec_runner.sh'
notifications:
  email:
    recipients:
      - diapriid@gmail.com
      - ellocodelassembler@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
