language: ruby
rvm:
  - 2.1.2
bundler_args: --without development
branches:
  only:
      - master
before_install: ./travis/before_install.sh
before_script: 
  - cp config/database.yml.example config/database.yml
  - psql -U postgres -c 'create role taxonworks_development login createdb superuser;' 
  - rake db:drop  
  - rake db:create
  #- ./travis/before_script.sh
  - rake db:migrate
  - rake db:migrate HPS_ENV=test 
notifications:
  email:
    - diapriid@gmail.com 
  on_failure: change
