 # This is used in the quick bar for navigation, it is meant to map closely related data classes together for quick access.  At most 3-4 classes should be used for each category.
---
otus: 
  - taxon_names
  - taxon_determinations
taxon_names: 
  - otus
  - taxon_name_relationships
taxon_name_relationships:
  - taxon_names
collection_objects:
  - collecting_events 
  - taxon_determinations
  - repositories
tags:
  - controlled_vocabulary_terms
repositories:
  - collection_objects
sources:
  - serials
  - people
serials: 
  - sources
  - people
geographic_areas:
  - collecting_events
  - georeferences
collecting_events:
  - georeferences
controlled_vocabulary_terms:
  - tags
  - data_attributes
people:
  - sources 
  - collecting_events
  - taxon_determinations
geographic_items:
  - geographic_areas
  - georeferences
  - collecting_events
loans:
  - collection_profiles
  - repositories  
