# This configuration file determines what is shown per object radial
# 
# The values here are returned as JSON via /metadata/radial/:klass
#
# Valid attributes (* required)
#   tasks: - A named task (see user_tasks.yml) !! Limit this to 3 or 4 
#   recent: - defaults to true if not provided, if false no recent list is shown
#   allow_destroy: - false if no
#   edit: over-ride data->edit
#   show: over-ride data->show
#
---
Source:
  tasks:
    - index_hub_task
    - new_verbatim_reference_task
    - nomenclature_by_source_task
    - index_individual_bibtex_source_task
  config:
    recent: true

