# All routes scoped to /tasks may be annotated here
# YAML is organized by:
#
# prefix: 
#   attribute: value
#   attribute: value
#
# Valid attributes (* required)
#   name* - a friendly human readable name describing the task
#   description - a sentence or two further defining what the task will do for the user
#   related_prefixes - array members must be route prefixes and may include user tasks or data prefixes
#   
---
nearby_locality_task:
  name: 
  related:
    - collecting_event
update_locality_task:
  name: 
within_locality_task:
  name: 
similar_serials_task:
  name: 
  related:
    - serial
update_serial_find_task:
  name: 
find_similar_serials_task:
  name: 
  related:
    - serials
return_similar_serials_task:
  name: 
user_activity_report_task:
  name: 
verify_accessions_task:
  name: 
quick_verbatim_material_task:
  name: 
create_verbatim_material_task:
  name: 
new_verbatim_reference_task:
  name: 
create_verbatim_reference_task:
  name: 
build_biocuration_groups_task:
  name:
  related: 
    - build_biocuration_group_task 
build_biocuration_group_task:
  name: 
  related: 
    - build_biocuration_groups_task

