# !! YOU MUST RESTART THE SERVER FOR CHANGES HERE TO TAKE AFFECT !!
# 
# All routes scoped to /tasks _may_ be further annotated here.
# YAML is organized by:
#
# prefix: 
#   attribute: value
#   attribute: value
#
# Valid attributes (* required)
#   name* - a friendly human readable name describing the task
#   description - a sentence or two further defining what the task will do for the user
#   related_prefixes - an array members must be route prefixes and may include user tasks or data prefixes
#   hub - true if this tasks should appear at the hub, these tasks MAY NOT require parameters
#
---
match_georeference_task:
  name:
  related:
    - collecting_events
    - georeferences
nearby_locality_task:
  name:  
  related:
    - collecting_events
    - geographic_areas
update_locality_task:
  name: 
within_locality_task:
  name:
similar_serials_task:
  name: 
  related:
    - serials
update_serial_find_task:
  name: 
find_similar_serials_task:
  name: 
  related:
    - serials
return_similar_serials_task:
  name: 
user_activity_report_task:
  name: 
verify_accessions_task:
  name: 
quick_verbatim_material_task:
  hub: true
  name: 'Quick verbatim material'
  description: 'Create new specimen or lot records with verbatim data only.' 
  related: 
    - namespaces
    - build_biocuration_groups_task
create_verbatim_material_task:
  name: 
new_verbatim_reference_task:
  hub: true 
  name: 'New source from citation.'
  description: 'Create a new source by pasting in the full text of a citation. The citation will automatically be tested against Crossref and parsed into individual fields (BibTex) if possible.'
create_verbatim_reference_task:
  name: 
build_biocuration_groups_task:
  hub: true
  name: 'Manage biocuration types and groups.'
  description: 'Create bio-curation categories that are used to organize physical collections (e.g. specimens and lots).'
  related: 
    - build_biocuration_group_task 
build_biocuration_group_task:
  name: 
  related: 
    - build_biocuration_groups_task
build_biocuration_group_task:
  name: 
  related: 
    - build_biocuration_groups_task
match_georeference_task:
  hub: true
  name: 'Match georeferences'
  description: 'Re-use georeference efforts from past collecting events.'
