---
apiVersion: v1
kind: Service
metadata:
  name: taxonworks
  namespace: tw
  labels:
    app: taxonworks
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: taxonworks
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: taxonworks
  namespace: tw
spec:
  replicas: 1
  template:
    metadata:
      namespace: tw
      name: taxonworks
      labels:
        app: taxonworks
        tier: frontend
    spec:
      containers:
        - name: taxonworks
          image: sfgrp/taxonworks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 3
          env:
            - name: SERVER_NAME
              value: mini
            - name: POSTGRES_HOST
              value: taxonworks-db
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: taxonworks
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taxonworks
                  key: db.user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taxonworks
                  key: db.user.password
            - name: NGINX_SECRET_KEY
              value: secret!
            - name: SECRET_KEY_BASE
              value: 169d48d8fbed4afeee626014caf67b036b11c30e00de424ba35e0d34ff29b358e635b25291c93ac674ebf76063d09ef1d8d153ade9de6e7c26b4120eeb35f8e4
          ports:
            - containerPort: 80
              name: http

