---
apiVersion: v1
kind: Service
metadata:
  name: taxonworks
  namespace: sandbox
  labels:
    app: taxonworks
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: taxonworks
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: taxonworks
  namespace: sandbox 
spec:
  replicas: 1 # must always be 1 in sandbox
  template:
    metadata:
      namespace: sandbox
      name: 
      valueFrom:
        configMapKeyRef:
          name: taxonworks
          key: db
          # name: taxonworks # value from (?) == tw-sandpaper (name of pod)
      labels:
        app: taxonworks
        tier: frontend
    spec:
      volumes:
        - name: taxonworks-staging-vol
          persistentVolumeClaim:
            claimName: taxonworks-staging-pv-claim
      containers:
        - name: taxonworks
          image: sfgrp/taxonworks:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /staging
              name: taxonworks-staging-vol
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 1500 # 30 
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 1500 # 180
            timeoutSeconds: 3
          env:
            - name: RAILS_ENV
              value: production
            - name: SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: server 
                  key: name 
              # value: sfg.taxonworks.org  # valueFrom
            - name: POSTGRES_HOST
              value: taxonworks-db # valueFrom
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: data  # was taxonworks
                  key: db
            - name: POSTGRES_USER
              value: sandbox
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taxonworks
                  key: db.user.password
            - name: NGINX_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: taxonworks 
                  key: nginx.secret 
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: taxonworks
                  key: secret_key_base
            - name: TW_EXCEPTION_NOTIFICATION_EMAIL_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.exception_notification.email_prefix
            - name: TW_EXCEPTION_NOTIFICATION_SENDER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.exception_notification.sender_address
            - name: TW_EXCEPTION_RECIPIENTS
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.exception_recipients
            - name: TW_ACTION_MAILER_SMTP_SETTINGS_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.action_mailer_smtp_settings.address
            - name: TW_ACTION_MAILER_SMTP_SETTINGS_PORT
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.action_mailer_smtp_settings.port
            - name: TW_ACTION_MAILER_SMTP_SETTINGS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.action_mailer_smtp_settings.domain
            - name: TW_ACTION_MAILER_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.action_mailer_url_host
            - name: TW_MAIL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.mail_domain
            - name: TW_PATHS_STAGING
              valueFrom:
                configMapKeyRef:
                  name: taxonworks 
                  key: tw.paths.staging
            - name: TW_PATHS_BACKUP
              valueFrom:
               configMapKeyRef:
                 name: taxonworks 
                 key: tw.paths.backup
