
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sandbox 
  name: sandbox-staging-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4700Gi
  selector:
    matchLabels:
      name: sandbox-staging-pv
