# This defines sets of related functionality, as displayed in the 'related' tabs.
# !! DO NOT ADD EMPTY ARRAYS  !!
#
# Valid attributes (* required)
#   status - one of [complete, stable, prototype, unknown (default) ] (see user_tasks.yml)
#   categories - an array of [CollectingEvent, CollectionObject, Source, TaxonName]
#   hide - default false
#   description - 
#
---
Core: # a Section
  Otu:  
    status: :prototype # A status
  TaxonName:
    status: :prototype
    categories:
      - TaxonName
  CollectingEvent:
    status: :prototype
    categories: 
      - CollectingEvent
  CollectionObject: 
     status: :prototype
     categories:
       - CollectionObject
  ControlledVocabularyTerm :
     status: :prototype
  Source:
     status: :prototype
     shared: true
  BiologicalAssociation:
     status: :prototype
Supporting:
  AssertedDistribution:
    categories:
      - Source 
  BiologicalAssociationsGraph:
  BiologicalRelationship:
  CollectionProfile:
  CollectionObjectObservation:
  Container:
    categories:
      - CollectionObject
  ContainerItem:
    categories:
      - CollectionObject
  Content:
  CommonName:
    categories:
      - TaxonName
  Document:
  Documentation:
  Depiction:
  Georeference:
    categories:
      - CollectingEvent 
  GeographicArea:
    shared: true
    application_defined: true
  Repository:
    shared: true
    application_defined: true
  Image:
    categories:
      - CollectionObject
  Loan:
    categories:
      - CollectionObject
  LoanItem:
    categories:
      - CollectionObject
  OtuPageLayout:
  Person:
    shared: true
  PreparationType:
    shared: true
  Namespace:
    shared: true
  RangedLotCategory:
  Serial:
    shared: true 
  TaxonDetermination:
  TaxonNameClassification:
   categories:
      - TaxonName 
  TaxonNameRelationship:
    categories:
      - TaxonName 
  TypeMaterial:
    categories:
      - TaxonName 
      - CollectionObject
Annotations:
  AlternateValue:
  Citation:
    categories:
      - Source 
  DataAttribute:
  Identifier:
  Note:
  Tag:





