# This defines sets of related functionality, as displayed in the 'related' tabs.
# !! DO NOT ADD EMPTY ARRAYS  !!
#
# Valid attributes (* required)
#   status - one of [complete, stable, prototype, unknown (default) ] (see user_tasks.yml)
#   categories - an array of one or more of [CollectingEvent, CollectionObject, Source, TaxonName]
#   hide - default false
#   description - 
#   related_models - an array of similar models
#
---
Core: # a Section
  Otu:  
    status: :prototype 
    related_models:
      - TaxonName
      - TaxonDetermination
  TaxonName:
    status: :prototype
    categories:
      - TaxonName
    related_models:
      - Otu
      - TaxonNameRelationship
  CollectingEvent:
    status: :prototype
    categories: 
      - CollectingEvent
    related_models:
      - Georeference
  CollectionObject: 
     status: :prototype
     categories:
       - CollectionObject
     related_models:
       - CollectingEvent
       - TaxonDetermination
       - Repository
  ControlledVocabularyTerm :
     status: :prototype
     related_models:
       - Tag
       - DataAttribute
  Source:
     status: :prototype
     shared: true
     categories:
       - Source 
     related_models:
       - Serial
       - People
  ProjectSource:
    related_models:
      - Source
      - Person 
    categories:
      - Source
  BiologicalAssociation:
     status: :prototype
     related_models:
       - BiologicalRelationship
Supporting:
  AssertedDistribution:
    categories:
      - Source 
  BiologicalAssociationsGraph:
    related_models:
      - Source
  BiologicalRelationship:
    related_models:
      - BiologicalAssociations
  CollectionProfile:
  CollectionObjectObservation:
  Container:
    categories:
      - CollectionObject
    related_models:
      - ContainerItem
  ContainerItem:
    categories:
      - CollectionObject
    related_models:
      - Container
  Content:
    related_models:
      - ControlledVocabularyTerm
  CommonName:
    categories:
      - TaxonName
  Document:
    related_models:
      - Documentation: documentation_index_path
  Documentation:
    related_models:
      - Document 
  Depiction:
    related_models:
      - Image
    categories:
      - CollectionObject
      - CollectingEvent
  Georeference:
    categories:
      - CollectingEvent 
  GeographicArea:
    shared: true
    application_defined: true
    related_models:
      - CollectingEvent
      - Georeference
    categories:
      - CollectingEvent
  GeographicItem:
    hide: true
    related_models:
      - GeographicArea
      - Georeference
      - CollectingEvent
  Image:
    categories:
      - CollectionObject
  Loan:
    categories:
      - CollectionObject
    related_models:
      - CollectionProfile
      - Repository
      - LoanItem
  LoanItem:
    categories:
      - CollectionObject
    related_models:
      - Loan
      - CollectionObject
      - Otu
  OtuPageLayout:
    related_models:
      - ControlledVocabularyTerm
  Person:
    shared: true
    related_models:
      - Source
      - CollectingEvent
      - TaxonDetermination
  PreparationType:
    shared: true
    categories:
      - CollectionObject
  Namespace:
    shared: true
  RangedLotCategory:
    categories:
      - CollectionObject
  Repository:
    shared: true
    application_defined: true
    related_models:
      - CollectingObject
  Serial:
    shared: true 
    categories:
      - Source 
    related_models:
      - Source
      - Person
  TaxonDetermination:
     categories:
       - CollectionObject
     related_models:
       - Otu 
       - CollectionObject
  TaxonNameClassification:
    categories:
      - TaxonName 
    related_models:
      - TaxonName
      - TaxonNameRelationship
  TaxonNameRelationship:
    categories:
      - TaxonName 
    related_model:
      - TaxonName
      - TaxonNameClassification
  TypeMaterial:
    categories:
      - TaxonName 
      - CollectionObject
Annotations:
  AlternateValue:
  Citation:
    categories:
      - Source 
  DataAttribute:
  Identifier:
  Note:
  Tag:
    related_models:
      - ControlledVocabularyTerm
