name: deliver

on:
  push:
    branches:
      - staged-imports
jobs:
  deliver:
    if: |
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[ci-skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[skip-ci]')
      )
    env:
      REF_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      CACHE_PATH: ".github/.docker-cache"

    runs-on: ubuntu-18.04
    steps:
    - name: Get startup date
      id: datetime
      run: echo "::set-output name=year_week::$(date -u +'%Y-%U')"

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up Docker images cache
      id: docker_cache
      uses: actions/cache@v2
      with:
        path: .github/.docker-cache
        key: ${{ runner.os }}-docker-${{ steps.datetime.outputs.year_week }}-${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ steps.datetime.outputs.year_week }}

    - name: Load Docker cache (if cache was hit)
      run: |
        [ ! -f ${CACHE_PATH}/images.tar ] || docker load -i ${CACHE_PATH}/images.tar

    - name: Build the Docker image
      run: docker build . -t sfgrp/taxonworks --build-arg REVISION=$(echo $GITHUB_SHA | cut -c1-9) --build-arg BUNDLER_WORKERS=3

    - name: Run image tests
      run: .github/docker-tests/test.sh

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      env:
        DOCKER_TAG: 'staged-imports'
      run: |
        docker tag sfgrp/taxonworks:latest sfgrp/taxonworks:$DOCKER_TAG
        docker push sfgrp/taxonworks:$DOCKER_TAG

    - name: Save Docker cache (if cache was NOT hit)
      env:
        CACHE_HASH: ${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}
      run: |
        mkdir -p $CACHE_PATH
        [ -f ${CACHE_PATH}/${CACHE_HASH} ] || docker save -o ${CACHE_PATH}/images.tar $(docker history -q sfgrp/taxonworks | grep -v '^<missing>')
        touch ${CACHE_PATH}/${CACHE_HASH}
